### ISSUE TITLE
Change `svelte top`'s sort-by option to be a boolean flag

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/svelte#14]
Right now it is `--sort-by (shallow|retained)` with default to `shallow`. But that means that one would never do `--sort-by shallow`, so this option only exists to enable sorting by retained size. So it should just be `-r/--retained` instead of the current behavior.

This mostly involves changing the option parsing in `opt/opt.rs`.

**Comment by sendilkumarn** [comment]
we are already using `-r` for retained_path, we can use the long path (`--retained`) alone here
